[dependencies]
numpy = "^1.4.1"
scipy = "^1.19.5"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.7.1",
    "cmake>=3.21",
    "scikit-build>=0.12",
    "ninja",
]

build-backend = "setuptools.build_meta"