[dependencies]
numpy = "^1.4.1"
scipy = "^1.19.5"
mkl = "^2021.3"
mkl-include = "^2021.3"
mkl-devel = "^2021.3"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.7.1",
    "cmake>=3.21",
    "scikit-build>=0.12",
    "mkl>=2021.3",
    "mkl-include>=2021.3",
    "mkl-devel>=2021.3",
]

build-backend = "setuptools.build_meta"